name: CMS Regression Tests
on: 
   workflow_dispatch:
    inputs:
      Tenant:
        description: 'Tenant against which tests execute,comma seperated Ex: ["api_client1_qa01","api_client2_qa01"]'
        type: string
        required: true
        default: '["api_client1_qa01","api_client2_qa01"]'    
jobs:
  GoogleAPI-Post:
    runs-on: ubuntu-latest
    env:
      REPORTS: testArtifact/google-reports
    strategy:
      matrix:
        realm: ${{ fromJson(github.event.inputs.Tenant) }}
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Create dir
        run: |          
          mkdir -p ${{ env.REPORTS }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      # - name: Install Azure CLI
      #   run: |
      #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Allure CLI
        run: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            curl -o allure-2.29.0.zip -LO https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.29.0/allure-commandline-2.29.0.zip
            sudo unzip allure-2.29.0.zip -d /opt/
            sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
        
      - name: Install newman
        continue-on-error: true
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-allure@2.1.0
          npm install -g allure-commandline
