name: Google Multitenant tests
on: 
   workflow_dispatch:
    inputs:
      Tenant:
        description: 'Tenant against which tests execute,comma seperated Ex: ["go_client1_qa01","go_client2_qa01"]'
        type: string
        required: true
        default: '["go_client1_qa01","go_client2_qa01"]'    
jobs:
  GoogleAPI-Post:
    runs-on: ubuntu-latest
    env:
      REPORTS: testArtifact/google-reports
    strategy:
      matrix:
        realm: ${{ fromJson(github.event.inputs.Tenant) }}
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Create dir
        run: |          
          mkdir -p ${{ env.REPORTS }}
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      # - name: Install Azure CLI
      #   run: |
      #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
